// Generated by CoffeeScript 2.7.0
//###########################################################
var blocked, blockingTimeMS;

blockingTimeMS = 10000;

//###########################################################
blocked = {};

//###########################################################
export var setBlockingTimeMS = function(timeMS) {
  if (typeof timeMS !== "number") {
    throw new Error("TimeMS was no number!");
  }
  blockingTimeMS = timeMS;
};

//###########################################################
export var blockOrThrow = function(key) {
  var stop;
  if (typeof key !== "string") {
    throw new Error("Key was no string!");
  }
  if (blocked[key]) {
    throw new Error(`Key ${key} is blocked!`);
  }
  blocked[key] = true;
  stop = function() {
    delete blocked[key];
  };
  setTimeout(stop, blockingTimeMS);
};

//###########################################################
export var isBlocked = function(key) {
  if (typeof key !== "string") {
    throw new Error("Key was no string!");
  }
  if (blocked[key]) {
    return true;
  }
  return false;
};

//###########################################################
export var passOrThrow = function(key) {
  if (typeof key !== "string") {
    throw new Error("Key was no string!");
  }
  if (blocked[key]) {
    throw new Error(`Key ${key} is blocked!`);
  }
};
