// Generated by CoffeeScript 2.7.0
//###########################################################
var blocked, blockingTimeMS;

blockingTimeMS = 10000;

//###########################################################
blocked = {};

//###########################################################
export var setBlockingTimeMS = function(timeMS) {
  return blockingTimeMS = timeMS;
};

//###########################################################
export var blockOrThrow = function(key) {
  var unblock;
  if (typeof key !== "string") {
    throw new Error("Key was no string!");
  }
  if (blocked[key]) {
    throw new Error(`Key ${key} is blocked!`);
  }
  blocked[key] = true;
  unblock = function() {
    delete blocked[key];
  };
  setTimeout(unblock, blockingTimeMS);
};
